// Correspondance societe -> nom de fichier PDF dans data/
// Genere le 2026-09-27 depuis kpis.db (companies.type)
export const PDF_PAR_SOCIETE: Record<string, string> = {
  "AG.Mut": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
  "AG2R Prevoyance": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
  "Abeille Epargne Retraite": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Abeille IARD Sante": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Abeille Vie": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Aema Groupe": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Aesio Mutuelle": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Allianz Vie": "Rapport_de_solvabilité_Allianz_Vie_2025.pdf",
  "Arpege Prevoyance": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
  "CNP Assurances": "sfcr_cnp_assurances_2025.pdf",
  "Cardif Assurance Vie": "Cardif-Assurance-Vie-–-Annexes-2025.pdf",
  "Cardif Assurances Risques Divers": "cardif-assurances-risques-divers-–-annexes-2025.pdf",
  "Covéa": "sfcr_covea_2025.pdf",
  "Crédit Agricole Assurances": "Groupe-Credit-Agricole-Assurances-–-SFCR-2025.pdf",
  "Groupama": "SFCR_2025_Groupe-Groupama.pdf",
  "La Mondiale": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
  "La Mondiale Europartner": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
  "La Mondiale Partenaire": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
  "MACIF SAM": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "MACSF prévoyance": "RAPPORT_SFCR_MACSF_prevoyance_2025.pdf",
  "MAIF": "rapport-solvabilite-maif-2025.pdf",
  "MGEN": "MGEN_SFCR_2025.pdf",
  "MMJ": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "MNPAF": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Macif Sante Prevoyance": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Macif Vie": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Macifilia": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Nuoma": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Predica": "PREDICA-–-SFCR-2025.pdf",
  "Prima": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
  "SGAM AG2R LA MONDIALE": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
  "Sogécap": "Rapport_de_solvabilite_2025_Sogécap_01.pdf",
  "Themis": "Aema-Groupe_RAPPORT-UNIQUE-SUR-LA-SOLVABILITE-ET-LA-SITUATION-FINANCIERE_2025.pdf",
  "Generali IARD": "Annexe_RSSF_QRT_GIARD_2025.pdf",
  "Generali Vie": "Annexe_RSSF_QRT_GVIE_2025.pdf",
  "VIASANTE Mutuelle": "AG2R-LA-MONDIALE-RSSF-Groupe-2025.pdf",
};
